# Generated by Django 4.2 on 2024-06-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check_net_speed", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInternetSpeed",
            new_name="UserInternetSpeedData",
        ),
    ]
